# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://localhost:4321"

[_.globalMeta]
title = "pupperemeritus"
description = "Retro-Inspired Theme & Built for Astro"
longDescription = "Zaggonaut is a retro-inspired theme for Astro, built using TypeScript, TailwindCSS, and Astro."
cardImage = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"
keywords = [
  "scientific compute",
  "linux",
  "astrophysics",
  "astrophotography",
  "guitar",
  "prog rock",
  "technology",
  "geospatial",
  "artificial intelligence",
  "machine learning",
  "progressive rock",
  "progressive metal",
  "astronomy",
  "time series",
  "performance",
  "vector databases",
  "data science",
  "git",
  "docker",
  "kubernetes",
  "shell",
  "motorcycle",
  "f1",
  "adventure",
  "music",
]

[_.blogMeta]
title = "Zaggonaut Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = ""
keywords = [
  "scientific compute",
  "linux",
  "astrophysics",
  "astrophotography",
  "guitar",
  "prog rock",
  "technology",
  "geospatial",
  "artificial intelligence",
  "machine learning",
  "progressive rock",
  "progressive metal",
  "astronomy",
  "time series",
  "performance",
  "vector databases",
  "data science",
  "git",
  "docker",
  "kubernetes",
  "shell",
  "motorcycle",
  "f1",
  "adventure",
  "music",
]
[_.projectMeta]
title = "Zaggonaut Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"
keywords = [
  "scientific compute",
  "linux",
  "astrophysics",
  "astrophotography",
  "guitar",
  "prog rock",
  "technology",
  "geospatial",
  "artificial intelligence",
  "machine learning",
  "progressive rock",
  "progressive metal",
  "astronomy",
  "time series",
  "performance",
  "vector databases",
  "data science",
  "git",
  "docker",
  "kubernetes",
  "shell",
  "motorcycle",
  "f1",
  "adventure",
  "music",
]
[_.notFoundMeta]
title = "Zaggonaut 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"

[_.hero]
title = "pupperemeritus"
subtitle = "Just one more <br/> who’s searching for <br/>The world that ought to be"
image = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "pupperemeritus"
githubProfile = "https://github.com/pupperemeritus"
twitterProfile = "https://twitter.com/pupperemeritus9"
linkedinProfile = "https://linkedin.com/sri-guru-datta-p"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"
