# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://sgdp.vercel.app"

[_.globalMeta]
title = "Sri Guru Datta Pisupati"
description = "All about me in a single website."
longDescription = "Everything about me (like 10%) in a single website."
cardImage = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"
keywords = [
  "scientific compute",
  "linux",
  "astrophysics",
  "astrophotography",
  "guitar",
  "prog rock",
  "technology",
  "geospatial",
  "artificial intelligence",
  "machine learning",
  "progressive rock",
  "progressive metal",
  "astronomy",
  "time series",
  "performance",
  "vector databases",
  "data science",
  "git",
  "docker",
  "kubernetes",
  "shell",
  "motorcycle",
  "f1",
  "adventure",
  "music",
]

[_.blogMeta]
title = "Sri Guru Datta's Blog"
description = "My endless rambling"
longDescription = "I will ramble on about tech, science, music and anything that catches my attention"
keywords = [
  "scientific compute",
  "linux",
  "astrophysics",
  "astrophotography",
  "guitar",
  "prog rock",
  "technology",
  "geospatial",
  "artificial intelligence",
  "machine learning",
  "progressive rock",
  "progressive metal",
  "astronomy",
  "time series",
  "performance",
  "vector databases",
  "data science",
  "git",
  "docker",
  "kubernetes",
  "shell",
  "motorcycle",
  "f1",
  "adventure",
  "music",
]
[_.projectMeta]
title = "Sri Guru Datta Pisupati's Projects"
description = "A list of my software, machine learning, scientific computing, music and miscellaneous projects"
longDescription = "A list of my software, machine learning, scientific computing, music and miscellaneous projects"
cardImage = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"
keywords = [
  "scientific compute",
  "linux",
  "astrophysics",
  "astrophotography",
  "guitar",
  "prog rock",
  "technology",
  "geospatial",
  "artificial intelligence",
  "machine learning",
  "progressive rock",
  "progressive metal",
  "astronomy",
  "time series",
  "performance",
  "vector databases",
  "data science",
  "git",
  "docker",
  "kubernetes",
  "shell",
  "motorcycle",
  "f1",
  "adventure",
  "music",
]
[_.notFoundMeta]
title = "Error 404"
description = "The page you are looking for does not exist. "
longDescription = "Oi, you're barkin' up the wrong tree. The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"

[_.hero]
title = "Sri Guru Datta Pisupati"
subtitle = "Just one more <br/> who’s searching for <br/>The world that ought to be"
image = "https://staging-jubilee.flickr.com/65535/49707414291_871a8a081a_q.jpg"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Sri Guru Datta Pisupati"
githubProfile = "https://github.com/pupperemeritus"
twitterProfile = "https://twitter.com/pupperemeritus9"
linkedinProfile = "https://linkedin.com/in/sri-guru-datta-p"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"
